// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetProject.DataAccess;

namespace PetProject.DataAccess.Migrations
{
    [DbContext(typeof(PetContext))]
    [Migration("20200125100008_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("PetProject.Domain.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("PetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ImageId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("PetProject.Domain.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PetStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolunteerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PetId");

                    b.HasIndex("PetStatusId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("PetProject.Domain.PetFeature", b =>
                {
                    b.Property<int>("PetFeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Characteristic")
                        .HasColumnType("TEXT");

                    b.HasKey("PetFeatureId");

                    b.ToTable("PetFeatures");
                });

            modelBuilder.Entity("PetProject.Domain.PetFeatureAssignment", b =>
                {
                    b.Property<int>("PetFeatureAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PetFeatureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PetFeatureAssignmentId");

                    b.HasIndex("PetFeatureId");

                    b.HasIndex("PetId");

                    b.ToTable("PetFeatureAssignments");
                });

            modelBuilder.Entity("PetProject.Domain.PetStatus", b =>
                {
                    b.Property<int>("PetStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("PetStatusId");

                    b.ToTable("PetStatuses");
                });

            modelBuilder.Entity("PetProject.Domain.PetTaskTypeAssignment", b =>
                {
                    b.Property<int>("PetTaskTypeAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PetTaskTypeAssignmentId");

                    b.HasIndex("PetId");

                    b.HasIndex("TaskTypeId");

                    b.ToTable("PetTaskTypeAssignments");
                });

            modelBuilder.Entity("PetProject.Domain.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskId");

                    b.HasIndex("PetId");

                    b.HasIndex("TaskTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("PetProject.Domain.TaskType", b =>
                {
                    b.Property<int>("TaskTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DefaultDuration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PetPoints")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskTypeId");

                    b.ToTable("TaskTypes");
                });

            modelBuilder.Entity("PetProject.Domain.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBlackListed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PetPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PetProject.Domain.UserFeature", b =>
                {
                    b.Property<int>("UserFeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<int>("Characteristic")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserFeatureId");

                    b.ToTable("UserFeature");
                });

            modelBuilder.Entity("PetProject.Domain.UserFeatureAssignment", b =>
                {
                    b.Property<int>("UserFeatureAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserFeatureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserFeatureAssignmentId");

                    b.HasIndex("UserFeatureId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFeatureAssignments");
                });

            modelBuilder.Entity("PetProject.Domain.UserSocialNetwork", b =>
                {
                    b.Property<int>("UserSocialNetworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<string>("NetworkType")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserSocialNetworkId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSocialNetworks");
                });

            modelBuilder.Entity("PetProject.Domain.Image", b =>
                {
                    b.HasOne("PetProject.Domain.Pet", "Pet")
                        .WithMany("Images")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetProject.Domain.Pet", b =>
                {
                    b.HasOne("PetProject.Domain.PetStatus", "PetStatus")
                        .WithMany("Pets")
                        .HasForeignKey("PetStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetProject.Domain.PetFeatureAssignment", b =>
                {
                    b.HasOne("PetProject.Domain.PetFeature", "PetFeature")
                        .WithMany("PetFeatureAssignments")
                        .HasForeignKey("PetFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetProject.Domain.Pet", "Pet")
                        .WithMany("PetFeatureAssignments")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetProject.Domain.PetTaskTypeAssignment", b =>
                {
                    b.HasOne("PetProject.Domain.Pet", "Pet")
                        .WithMany("PetTaskTypeAssignments")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetProject.Domain.TaskType", "TaskType")
                        .WithMany("PetTaskTypeAssignments")
                        .HasForeignKey("TaskTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetProject.Domain.Task", b =>
                {
                    b.HasOne("PetProject.Domain.Pet", "Pet")
                        .WithMany("Tasks")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetProject.Domain.TaskType", "TaskType")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetProject.Domain.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetProject.Domain.UserFeatureAssignment", b =>
                {
                    b.HasOne("PetProject.Domain.UserFeature", "UserFeature")
                        .WithMany("UserFeatureAssignments")
                        .HasForeignKey("UserFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetProject.Domain.User", "User")
                        .WithMany("UserFeatureAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetProject.Domain.UserSocialNetwork", b =>
                {
                    b.HasOne("PetProject.Domain.User", "User")
                        .WithMany("UserSocialNetworks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
